#167292973: modify chat section to stop scrolling from affecting the left panel
AndelaOSP/wire pull request #198
Opened 2019-07-16 11:54 UTC by billkabanga

#### What does this PR do?
modify the chat section to stop scrolling from affecting the left panel ie timeline sidebar.

#### Description of Task to be completed?
- set overflow style of the body to hidden to stop scrolling of the full page.
- set height of sidebar container to 100vh and overflow to auto.
- set timeline main content section to a height and overflow of auto.
- give the chat container height of 35vh.

#### How should this be manually tested?
- Clone this project
- checkout this branch `ft-chat-panel-scroll-167292973`
- Run the application.
- Log in to the application and select a single incident.
- Click on an incident of choice.
- Follow GIF(for after) below.

#### What are the relevant pivotal tracker stories?
[#167292973](https://www.pivotaltracker.com/story/show/167292973)
#### Screenshots (if appropriate)

#### Before:
![wire1](https://user-images.githubusercontent.com/40595048/61292246-6245e380-a7d9-11e9-8135-3640fc6d2179.gif)

#### After:
![afterWire](https://user-images.githubusercontent.com/40595048/61292257-68d45b00-a7d9-11e9-9614-57dd7194fced.gif)

2019-07-26 12:22 UTC, ah-med requested changes
Looks Good

2019-07-26 12:22 UTC, ah-med commented on src/Components/TimelineChat/TimelineChat.scss
> +  height: 35vh !important;
is it possible we do away with `!important` here?

2019-07-26 14:12 UTC, ah-med approved these changes

2019-07-30 08:31 UTC, tejiri4 approved these changes
LGTM

2019-07-30 12:49 UTC, actlikewill approved these changes
Looks good.

2019-07-31 16:32 UTC, merged